<style type="text/css">
	
	.wphb_form_field {
		width: 100%;
		display: flex;
		flex-direction: row;
		justify-content: flex-start;
		align-items: center;
	}
	.wphb_form_field input {
		width: 100%;
	}
	.wphb_form_left {
		width: 50% !important;
		flex-grow: 0;
		flex-shrink: 0;
	}
	.wphb_form_right {
		width: 50% !important;
		flex-grow: 0;
		flex-shrink: 0;
	}

	.wphb_table {
		width: 100%;
		border-spacing: 0px;
		border-collapse: collapse;
	}
	.wphb_table input {
		min-height: unset !important;
	}
	.wphb_table select {
		width: 100%;
		max-width: unset !important;
	}
	.col0 {
		width: 50%;
	}
	.col1 {
		width: 50%;
	}
	
</style>			
			
<?php echo $this->writeBackendMessage(); ?>
	
<div class="wrap">
	<div id="icon-options-general" class="icon32">
		<br>
	</div>
	<h2><?php echo __('WpShopGermany - Händlerbund Integration', 'wphb'); ?></h2>
				
	<form method="POST" class="wphb_form">
		
		<?php echo $this->showForm(); ?>
		
		<div class="wphb_clear"></div>
		<br />
		<input type="submit" value="<?php echo __('Speichern', 'wphb'); ?>" name="wphb_submit" class="button-primary" />
		
	</form>
</div>